from django.db import models
from appbasic.models import Account
# Create your models here.
select=(("Yes","Yes"),("No","No"))
types = (("Live","Live"),("Test","Test"),("Both","Both"))

class mdl_customer(models.Model):
    account = models.OneToOneField(Account, on_delete=models.CASCADE,null=True,blank=True)
    customer_id=models.CharField(verbose_name="Customer Number",max_length=200)
    name=models.CharField(verbose_name="Customer Name",max_length=200,null=True,blank=True)
    address=models.CharField(verbose_name="Address",max_length=200,null=True,blank=True)
    city=models.CharField(verbose_name="City",max_length=200,null=True,blank=True)
    country=models.CharField(verbose_name="Country",max_length=200,null=True,blank=True)
    prov_state=models.CharField(verbose_name="Prov/State",max_length=200,null=True,blank=True)
    postal_zip=models.CharField(verbose_name="Postal_Zip",max_length=200,null=True,blank=True)
    fst=models.CharField(verbose_name="FST",max_length=200,null=True,blank=True)
    pst=models.CharField(verbose_name="PST",max_length=200,null=True,blank=True)
    phone=models.CharField(verbose_name="Phone",max_length=200,null=True,blank=True)
    fax=models.CharField(verbose_name="Fax",max_length=200,null=True,blank=True)
    ship=models.CharField(verbose_name="Ship Via",max_length=200,null=True,blank=True)
    sort=models.CharField(verbose_name="Sort Name",max_length=200,null=True,blank=True)
    contact=models.CharField(verbose_name="Contact",max_length=200,null=True,blank=True)
    terms=models.IntegerField(verbose_name="Terms Code",null=True,blank=True)
    gst=models.CharField(choices=select,default="Yes",verbose_name = "GST",max_length=100)
    usa=models.CharField(choices=select,default="Yes",verbose_name = "USA Account",max_length=100)
    discount=models.FloatField(verbose_name="Discount",null=True,blank=True)
    Oceanview_discount=models.FloatField(verbose_name="Oceanview Door Discount",null=True,blank=True)
    vista_discount=models.FloatField(verbose_name="Vista Door Discount",null=True,blank=True)
    credit=models.FloatField(verbose_name="Credit Limit",null=True,blank=True)
    date_opened=models.DateField(verbose_name="Date Opened",null=True,blank=True)
    mp=models.FloatField(verbose_name="MP Lock Price",null=True,blank=True)
    free=models.CharField(choices=select,default="Yes",verbose_name = "Free MP Lock",max_length=100)
    fh=models.FloatField(verbose_name="FH Price",null=True,blank=True)
    remark1=models.CharField(verbose_name="Remark1",max_length=200,blank=True)
    remark2=models.CharField(verbose_name="Remark2",max_length=200,blank=True)
    remark3=models.CharField(verbose_name="Remark3",max_length=200,blank=True)
    remark4=models.CharField(verbose_name="Remark4",max_length=200,blank=True)
    remark5=models.CharField(verbose_name="Remark5",max_length=200,blank=True)
    email1=models.CharField(verbose_name="Email #1",max_length=200,blank=True)
    email2=models.CharField(verbose_name="Email #2",max_length=200,blank=True)
    mobile1=models.CharField(verbose_name="Mobile #1",max_length=200,blank=True)
    mobile2=models.CharField(verbose_name="Mobile #2",max_length=200,blank=True)
    pst_rate=models.FloatField(verbose_name="PST Rate",null=True,blank=True)
    gst_rate=models.FloatField(verbose_name="GST Rate",null=True,blank=True)
    hst_rate=models.FloatField(verbose_name="HST Rate",null=True,blank=True)
    total_only_on_order=models.CharField(choices=select,default="Yes",verbose_name = "Total only on order Acknoledement",max_length=100)
    total_only_on_qutes=models.CharField(choices=select,default="Yes",verbose_name = "Total only on Qutes",max_length=100)
    wite=models.FloatField(verbose_name="Wite packing charge",null=True,blank=True)
    color=models.FloatField(verbose_name="Colour packing charge",null=True,blank=True)
    glass=models.FloatField(verbose_name="Glass only packing charge",null=True,blank=True)
    outside_color=models.FloatField(verbose_name="Outside colour #8 upcharge",null=True,blank=True)
    account_type=models.CharField(choices=types,verbose_name = "Account Type",max_length=200,null=True,blank=True)
    account_representative_name=models.CharField(verbose_name="Account Representative name",max_length=200,null=True,blank=True)
    account_representative_phone=models.CharField(verbose_name="Account Representative phone extension number",max_length=200,null=True,blank=True)
    account_representative_cell_phone=models.CharField(verbose_name="Account Representative cell phone",max_length=200,null=True,blank=True)
    account_representative_mail1=models.CharField(verbose_name="Account Representative email1",max_length=200,null=True,blank=True)
    account_representative_mail2=models.CharField(verbose_name="Account Representative email2",max_length=200,null=True,blank=True)

    class Meta:
        verbose_name=u"Customer"
    def __str__(self):
        return "%s" % (self.name)
