# Generated by Django 3.2.1 on 2021-05-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasic', '0008_settings_loading_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_part', models.CharField(blank=True, max_length=100, null=True, verbose_name='URBAN PART')),
                ('window_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='WINDOW TYPE')),
            ],
            options={
                'verbose_name': 'Setting',
            },
        ),
    ]
