# Generated by Django 3.2.1 on 2021-05-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasic', '0009_exceptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=100, verbose_name='Start Date')),
                ('end_date', models.CharField(max_length=100, verbose_name='End Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='exceptions',
            options={'verbose_name': 'Exceptions'},
        ),
    ]
