# Generated by Django 3.1.7 on 2021-04-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_window_item',
            name='tiger_stop_material',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='TIGER STOP MATERIAL'),
        ),
        migrations.AlterField(
            model_name='mdl_window_item',
            name='tiger_stop_part',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TIGER STOP PART'),
        ),
    ]
